---
- name: Install Docker
  hosts: manager,worker
  roles:
    - docker

- name: Run Prometheus, Grafana and Loki
  hosts: manager
  roles:
    - loki
    - grafana
    - prometheus

- name: Run Node Exporter and Promtail
  hosts: worker
  roles:
    - promtail
    - node_exporter
