---
- name: Run Node Exporter container
  changed_when: false
  ansible.builtin.shell: |
    docker rm node_exporter -f || true
    docker run -d \
      --name node_exporter \
      --restart unless-stopped \
      --net="host" \
      --pid="host" \
      -v "/:/host:ro,rslave" \
      --log-driver=loki \
      --log-opt loki-url="{{ loki_url }}" \
      --log-opt loki-retries=5 \
      --log-opt loki-batch-size=400 \
      {{ images.node_exporter }} \
      --path.rootfs=/host
  
- name: Add extra prometheus configs
  tags: "extra-configs"
  delegate_to: "{{ groups['manager'][0] }}"
  become: true
  become_user: root
  ansible.builtin.template:
    src: "scrape_config.yml.j2"
    dest: "/etc/prometheus/scrapes/node_exporter_{{ inventory_hostname }}.yml"
    mode: "0777"
    group: docker
